body {
  padding-top: 0rem !important;
  background-color: white !important;
}
#wrapper{
  max-width: 90% !important;
  border: none !important;
  border-radius: 0px !important;
  background: white !important;
}
#primary {
  width: 60% !important;
}

#header{
   border-radius: 0px; 
}

#header #site-logo {
  margin: 0 2% !important;
  padding: 0.4em 0 !important;
}

#slider-wrap a {
    padding: 0px 0px 0px !important;
    margin-top: 1.7% !important;
}

#nav-slider .nav-next {
    right: 1px !important;
}

#nav-slider .nav-previous {
    left: 1px !important;
}

#main {
    width: 98% !important;
    padding: 1% !important;
}

.social-profile {
    top: 1.3em !important;
}

#preface-area {
  background-color: white !important;
}

#main {
  background-color: white !important;
}

#content {
  width: 100% !important;
}

#sidebar{
  width: 35% !important;
  margin-right: 2%;
}
ul li.facebook a {
    background-position: 0 -44px !important;
}
ul li.twitter a {
    background-position: -44px -44px !important;
}

ul li.google-plus a {
    background-position: -88px -44px !important;
}
ul li.pinterest a {
    background-position: -132px -44px !important;
}
ul li.rss a {
    background-position: -176px -44px !important;
}
#block-views-blog-list-block-1 h2{
  font-size: 25px;
  padding: 0 1em 0em !important;
  margin: 0 -0.75em 0.1em !important;
}

#block-views-blog-list-block-1{
  padding: 0.5em 2em 1em !important;
}

#block-views-blog-list-block-1 .field-content a{
  font-size: 16px !important;
}

#slider-wrap .bottom-left {
  position: absolute;
  bottom: 6%;
  left: 6%;
  color: white;
  font-size: 20px;
}

.iconDetails {
 margin-left:2%;
float:left; 
height:40px;
width:40px; 
} 

.container2 {
  width:270px;
  height:auto;
  padding:1%;
  float:left;
}
h4{
  margin:0
}
.left {
  float:left;width:45px;
}
.right {
  float:left;
  margin:0 0 0 5px;
  width:215px;
}

.most_popular_articles {
    width: 94% !important;
    float: left  !important;
    padding: 10px  !important;
    padding-bottom: 0  !important;
    margin-bottom: 40px  !important;
}

.most_popular_articles .most_popular_articles_head {
    font-size: 26px;
    float: left;
    width: 100%;
    text-align: center;
    font-family: "Gotham Narrow Medium";
    margin-bottom: 10px;
    padding-top: 15px;
}

.most_popular_articles ul.tabs {
    padding: 7px 0;
    margin: 0;
    font-size: 0;
    list-style-type: none;
    text-align: left;
    padding-left: 20px;
    float: left;
    width: 100%;
}

.most_popular_articles ul.tabs li {
    display: inline;
    margin: 0;
    background: White;
    margin-left: -4px;
    float: left;
    width: 50%;
}

div.tabcontents {
    float: left;
    width: 100%;
    padding: 0px;
}

.most_popular_articles .most_popular_article {
    float: left;
    width: 100%;
    padding: 10px 0;
    padding-bottom: 0;
}

.most_popular_articles .most_popular_article .most_popular_article_row {
    float: left;
    width: 100%;
    margin-bottom: 30px;
}

.most_popular_articles .most_popular_article .most_popular_article_row .most_popular_article_image {
    min-width: 120px;
    min-height: 55px;
    width: 120px;
    float: left;
}

.most_popular_articles .most_popular_article .most_popular_article_row .most_popular_article_details {
    float: left;
    width: 56%;
    padding-left: 15px;
}

.most_popular_articles .most_popular_article .most_popular_article_row .most_popular_article_details .most_popular_article_parent {
    float: left;
    width: 100%;
    text-transform: uppercase;
    font-size: 18px;
    font-family: "Gotham Narrow Medium";
}

.theme_yellow-text {
    color: #e0ba23 !important;
}

.most_popular_articles .most_popular_article .most_popular_article_row .most_popular_article_details .most_popular_article_head {
    float: left;
    width: 100%;
    font-size: 16px;
    font-family: "Gotham Narrow Medium";
}

#slider {
    background-color: #eee;
    border: none;
}

.most_popular_articles {
    width: 100%;
    float: left;
    padding: 10px;
    padding-bottom: 0;
    border: solid 1px #ccc;
    margin-bottom: 40px;
    margin-top: 3%;
}

.most_popular_articles .most_popular_articles_head {
    font-size: 26px;
    float: left;
    width: 100%;
    text-align: center;
    font-family: "Gotham Narrow Medium";
    margin-bottom: 10px;
    padding-top: 15px;
}

.most_popular_articles .blogcontents {
    float: left;
    width: 100%;
    padding: 0px;
}

.most_popular_article {
    float: left;
    width: 100%;
    padding: 10px 0;
    padding-bottom: 0;
}

.most_popular_articles .most_popular_article .most_popular_article_row {
    float: left;
    width: 100%;
}

.most_popular_articles .most_popular_article .most_popular_article_row .most_popular_article_image {
    min-width: 120px;
    min-height: 55px;
    width: 120px;
    float: left;
}

.most_popular_articles .most_popular_article .most_popular_article_row .most_popular_article_details {
    float: left;
    width: 56%;
    padding-left: 15px;
}

.most_popular_articles .most_popular_article .most_popular_article_row .most_popular_article_details .most_popular_article_parent {
    float: left;
    width: 100%;
    text-transform: uppercase;
    font-size: 18px;
    font-family: "Gotham Narrow Medium";
}

.most_popular_articles .most_popular_article .most_popular_article_row .most_popular_article_details .most_popular_article_head {
    float: left;
    width: 100%;
    font-size: 16px;
    font-family: "Gotham Narrow Medium";
}

.most_popular_articles .most_popular_article.no_cat_title .most_popular_article_head {
    max-height: 44px;
    overflow: hidden;
}

.most_popular_articles .most_popular_article .most_popular_article_row .most_popular_article_details .most_popular_article_head a {
    font-family: "Gotham Narrow Medium";
}

.theme_hit_pink-text {
    color: #e27b64 !important;
}

.full-width-carousel .content, #landing-pages-content {
    max-width: 1170px;
    margin: 0 auto;
    float: none !important;
    clear: both;
    position: relative;
}

.fl-lp-gallery-wrap {
    margin-bottom: 0 !important;
    padding-bottom: 0 !important;
    font-size: 0;
}

.fl-lp-gallery-wrap {
    position: relative;
}
.fl-lp-gallery-wrap {
    text-align: center;
    margin: 0;
}

.div_FullCarouselComponent .lp_full_carousel {
    position: relative;
    width: 100%;
}

.field-slideshow-lp-gallery {
    position: relative;
    display: inline-block;
    text-align: left;
}

.div_FullCarouselComponent .lp_full_carousel .lp_carousel_fld_outer {
    width: 100%;
}

.lp_carousel_fld_outer {
    z-index: 95 !important;
}

.lp_carousel_fld_img {
    padding: 0 0 0 0;
    overflow: hidden;
}

.div_FullCarouselComponent .lp_full_carousel img {
    position: relative;
    width: 100%;
    max-width: none;
}

#navigation{
  width: 95% !important;
  background-color: white !important;
  background: white !important;
  color: #000 !important;
  float: none !important;
}

#header{
  border-bottom: solid 8px #fcd34a;
}

#navigation li{
  border: none !important;
}

#navigation a{
  color: #000 !important; 
}

#footer-area {
    background-color: white !important;
}

